### ISSUE TITLE
Edit todo function

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/todolist-nextjs#4]
- [x] Show and hide input
- [x] Edit database function
- [x] Edit API route
- [x] Edit frontend stuff
