### ISSUE TITLE
Delete todo function

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/todolist-nextjs#5]
- [x] Edit database function
- [x] Edit API function
- [x] Edit frontend stuff
